### ISSUE TITLE
Unpredictable Node IP addresses

### ISSUE THREAD

**Issue by benschmi** [openelb/openelb#221]
Hi,
my nodes have two interface, one public interface, for which I want to use my cloud providers CCM LB and one private interface for which I want to use OpenELB in layer 2 mode. According to the documentation I need to annotate my nodes with `layer2.porter.kubesphere.io/v1alpha1="<node_IP>"`.
However, due to cluster autoscaling, new nodes are constantly being added to and deleted from my cluster. The IP addresses of new nodes are not predictable in my environment. How would I go about?

**Comment by zheng1** [comment]
At the moment you can only add annotations to the node manually.  But I thought of a way for you to see if it solves your problem: **add a configuration item that uses a regex to match the NIC name**

Can you give me some advice? @benschmi

**Comment by benschmi** [comment]
Hi @zheng1 ,  thanks for your reply.
Unfortunately, in my environment the NIC name is not predictable since it's based on the virtual PCI-slot.
You need to identify the correct NIC, right? Why not use the network CIDR for identification? So instead of an individual IP address you allow the user to set the IP subnet in CIDR format.

**Comment by chaunceyjiang** [comment]
@benschmi @zheng1 
I think we should listen to all interfaces.
That might sound like a problem, but because of the way ARP works, only clients on the right network will know to look for the service IP on the network.
