### ISSUE TITLE
[CNCF Check List] Migrate project to OpenELB org

### ISSUE THREAD

**Issue by liangyuanpeng** [openelb/openelb#227]
OpenELB is CNCF project now and we need migrate project to [OpenELB org](https://github.com/openelb) for [CNCF check list of OpenELB](https://github.com/cncf/toc/issues/743)

**Comment by FeynmanZhou** [comment]
> /cc @FeynmanZhou

Yes, I will migrate this repo to OpenELB org soon. @zheng1 Could you please verify if this migration has no effect on the current project usage.

**Comment by zheng1** [comment]
@FeynmanZhou LGTM, please do it

**Comment by FeynmanZhou** [comment]
Hi team,

I have transferred the OpenELB repo to the [OpenELB organization](https://github.com/openelb/openelb) as CNCF is needed.
