### ISSUE TITLE
feature request: support assign eip by default with a config to controller

### ISSUE THREAD

**Issue by lxm** [openelb/openelb#231]
In most public iaas provider , we can create a service with `LoadBlancer` type to get a external IP for services.

Currently ,we must set some annotations to the service so that `openelb` will assign a external ip to the service.

How about add a config for the controller, like `AllService: true`, so that openelb will process all the service with `LoadBlancer` type

**Comment by FeynmanZhou** [comment]
IMO, this feature request is reasonable, it is necessary to implement it before we [integrate OpenELB to KubeSphere](https://github.com/kubesphere/kubesphere/issues/4574).

**Comment by chaunceyjiang** [comment]
> 
> How about add a config for the controller, like AllService: true, so that openelb will process all the service with LoadBlancer type


Maybe that's what you want?

https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class

**Comment by chaunceyjiang** [comment]
If `allservice: true` is assigned,  openelb will use what protocol  to process all Service?  layer2?
