### ISSUE TITLE
Rename porterlb to openelb

### ISSUE THREAD

**Issue by zheng1** [openelb/openelb#241]
Although we have changed the name of the project to openelb. But there are still many things that need to be corrected.

- [ ] porter in the code
- [ ] porter in the website
- [ ] porter in the URL
- [ ] porter in the documentation
- [ ] porter in the docker image repo

**Comment by FeynmanZhou** [comment]
How's this issue going?

**Comment by FeynmanZhou** [comment]
> Although we have changed the name of the project to openelb. But there are still many things that need to be corrected.
> 
> * [ ]  porter in the code
> * [ ]  porter in the website
> * [ ]  porter in the URL
> * [ ]  porter in the documentation
> * [ ]  porter in the docker image repo

IMO, the [Helm chart](https://github.com/kubesphere/helm-charts/tree/master/src/test/porter) is also supposed to be renamed and moved to this organization.

**Comment by renyunkang** [comment]
The code has been changed, I am testing

> 

I am changing the code and testing

**Comment by renyunkang** [comment]
> How's this issue going?

I am changing the code and testing

**Comment by renyunkang** [comment]
This issue has been resolved with these prs:

- https://github.com/kubesphere/helm-charts/pull/215
- https://github.com/openelb/openelb/pull/242
- https://github.com/openelb/website/pull/52

so I close it.
/close
