### ISSUE TITLE
kubesphere安装openelb之后 应用路由的网关ip本地可以访问，服务的LoadBalancer地址无法访问

### ISSUE THREAD

**Issue by liu01100115** [openelb/openelb#250]
访问应用路由的网关地址可以访问到
![image](https://user-images.githubusercontent.com/32833737/157012851-68645103-6fff-4bb6-980a-9641879b97e9.png)

![image](https://user-images.githubusercontent.com/32833737/157012814-b2ce9b5b-78da-4a59-af28-bb6785a2c951.png)

访问服务的LoadBalancer地址无法访问

![image](https://user-images.githubusercontent.com/32833737/157012885-25e3cb49-620b-4ced-9fe7-7ade2faa03f7.png)

![image](https://user-images.githubusercontent.com/32833737/157012937-dff1a445-f8dd-4246-9cfa-cb9a04fb5cf1.png)

**Comment by renyunkang** [comment]
Can you show the ip information of this machine and the yaml file of all related resources? eg: eip, service, Ingress.

**Comment by liu01100115** [comment]
![image](https://user-images.githubusercontent.com/32833737/157150368-468bb9df-927f-42ce-80bb-546d9d27d440.png)

![image](https://user-images.githubusercontent.com/32833737/157150389-cc747ea6-278b-4ba1-9010-8807f0a71a67.png)



service.yaml
kind: Service
apiVersion: v1
metadata:
  name: influxd-dev-office-influxdb
  namespace: middleware-longhui
  labels:
    app.kubernetes.io/component: influxdb
    app.kubernetes.io/instance: influxd-dev-office
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: influxdb
    app.kubesphere.io/instance: influxd-dev-office
    eip.openelb.kubesphere.io/v1alpha2: layer2-eip
    helm.sh/chart: influxdb-4.0.0
  annotations:
    eip.openelb.kubesphere.io/v1alpha2: layer2-eip
    kubesphere.io/alias-name: influxd-dev-office-influxdb
    kubesphere.io/creator: liuhongbo
    kubesphere.io/description: influxd-dev-office-influxdb
    layer2.openelb.kubesphere.io/v1alpha1: dev-kube-m-9-123
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: layer2
  finalizers:
    - finalizer.lb.kubesphere.io/v1alpha1
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: http
      nodePort: 32181
    - name: rpc
      protocol: TCP
      port: 8088
      targetPort: rpc
      nodePort: 31604
  selector:
    app.kubernetes.io/component: influxdb
    app.kubernetes.io/instance: influxd-dev-office
    app.kubernetes.io/name: influxdb
  clusterIP: 10.10.8.244
  clusterIPs:
    - 10.10.8.244
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack



ingrees.yaml

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: devnacos
  namespace: middleware-longhui
  annotations:
    kubesphere.io/creator: liuhongbo
spec:
  rules:
    - host: devnacos.test.cn
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: nacos
                port:
                  number: 8848

**Comment by liu01100115** [comment]
> 

我把layer2.openelb.kubesphere.io/v1alpha1指向到master节点好像就可以访问了

**Comment by renyunkang** [comment]
The annotation `layer2.openelb.kubesphere.io/v1alpha1` indicates which is the nexthop routing node when accessing the pod. Your issue is that the service cannot be accessed, not the pod.

**Comment by renyunkang** [comment]
Maybe the service is being deleted when you ping the service's ip. Can you describe the steps to reproduce this bug?
