### ISSUE TITLE
手动删除出现 Internal error occurred: failed calling webhook "mutating.eip.network.kubesphere.io": Post "https://openelb-0cb15g-manager....": service "openelb-0cb15g-manager" not found

### ISSUE THREAD

**Issue by gzymomo** [openelb/openelb#251]
helm 安装 0.4.4 版本
在kubeshere 页面上删除，工作负载和任务
出现问题：集群无法更新svc ，无法创建新的deplyemnt 等
![image](https://user-images.githubusercontent.com/22019924/157185894-ff0a60a1-8d6c-49d9-ab7e-76fde478a07a.png)

已尝试删除所有openelb相关资源，EIP 配置文件无法删除
```
[root@master gateway]# kubectl get eips.network.kubesphere.io -o yaml
apiVersion: v1
items:
- apiVersion: network.kubesphere.io/v1alpha2
  kind: Eip
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"network.kubesphere.io/v1alpha2","kind":"Eip","metadata":{"annotations":{},"name":"layer2-eip"},"spec":{"address":"172.16.84.240-172.16.84.245","interface":"ens3","protocol":"layer2"}}
    creationTimestamp: "2022-03-07T07:37:50Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2022-03-08T06:10:21Z"
    finalizers:
    - finalizer.ipam.kubesphere.io/v1alpha1
    generation: 2
    name: layer2-eip
    resourceVersion: "46872772"
    uid: 5842db6e-3111-4d05-8f29-f7c0d7250adf
  spec:
    address: 172.16.84.240-172.16.84.245
    interface: ens3
    protocol: layer2
  status:
    firstIP: 172.16.84.240
    lastIP: 172.16.84.245
    poolSize: 6
    ready: true
    usage: 2
    used:
      172.16.84.240: open-lb/openelb
      172.16.84.241: istio-system/istio-ingressgateway
    v4: true
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

请问如果想彻底删除，还需要删除哪些资源，或者恢复集群网络正常

**Comment by gzymomo** [comment]
删除 MutatingWebhookConfiguration 然后就好了
```
kubectl delete MutatingWebhookConfiguration xxx
```

**Comment by gzymomo** [comment]
EIP 资源还是无法删除，显示有两个使用，如何释放该资源
![image](https://user-images.githubusercontent.com/22019924/157204973-cf435d2d-314a-4679-938a-d4c9fb60ba55.png)

两个Load Balancer的service 无法删除

**Comment by gzymomo** [comment]
It works, i just delete the  finalizers field  and it disappear

> You can delete the `finalizers` field in the yaml with `kubectl edit eip xxx` and try to delete it again.

**Comment by ivanmissu** [comment]
@renyunkang  when i delete the finalizers field in the yaml with kubectl edit eip xxx, tips error: eips.network.kubesphere.io "porter-layer2-eip" could not be patched: Internal error occurred: failed calling webhook "validate.eip.network.kubesphere.io": Post "https://porter-32gjb1-manager.develops-components.svc:443/validate-network-kubesphere-io-v1alpha2-eip?timeout=10s": service "porter-32gjb1-manager" not found
You can run `kubectl replace -f /tmp/kubectl-edit-bg5ql.yaml` to try this update again.

**Comment by FeynmanZhou** [comment]
I also met the same issue in OpenELB 0.4.4. Can we provide an uninstallation script for OpenELB？It will also remove all resources created by OpenELB in the K8s cluster.

**Comment by renyunkang** [comment]
Sounds good, we'll discuss your suggestions.

**Comment by amal-thundiyil** [comment]
> 删除 MutatingWebhookConfiguration 然后就好了
> 
> ```
> kubectl delete MutatingWebhookConfiguration xxx
> ```

Alternative solution which worked for me. Change `openelb-admission` to the name of corresponding `mutatingwebhookconfiguration` and then:
```sh
kubectl edit mutatingwebhookconfigurations openelb-admission 
```
Now, set the `failurePolicy` from `Fail` to:
```yaml
failurePolicy: Ignore
```

**Comment by FeynmanZhou** [comment]
> 

@amal-thundiyil Thanks. This is a workaround. Now @renyunkang has provided a uninstall script to remove these resources and configuration.
