### ISSUE TITLE
根据文档创建后在ip neigh中没有找到LoadBalancer地址

### ISSUE THREAD

**Issue by ivanmissu** [openelb/openelb#254]
根据文档创建后在ip neigh中没有找到LoadBalancer地址, 而且为什么ip neigh显示的mac地址都是一样的 ，4台腾讯云服务器
node：
<img width="577" alt="image" src="https://user-images.githubusercontent.com/8721615/160395723-36768ebc-f0b1-40dd-917a-bb5acba3f038.png">
svc:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/8721615/160395385-2af7d70e-7a3e-415b-962e-de8211172473.png">
ip neigh:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/8721615/160395451-6270bc59-5a19-45e4-bee0-c756172f531a.png">
不过LoadBalancer地址是可以通的：
<img width="531" alt="image" src="https://user-images.githubusercontent.com/8721615/160396507-72a6a9ba-213a-470a-839b-90493b0e7673.png">

**Comment by renyunkang** [comment]
You should not check the arp table on the nodes of the kubernetes cluster, you should check it on the client machine.

**Comment by renyunkang** [comment]
You should not check the arp table on the nodes of the kubernetes cluster, you should check it on the client machine.

**Comment by ivanmissu** [comment]
> You should not check the arp table on the nodes of the kubernetes cluster, you should check it on the client machine.

yeah , i checked on client machine , it works.

**Comment by ivanmissu** [comment]
> When accessing services within the cluster, the access is achieved through ipvs or iptables instead of openelb.
ok, thanks for answering

**Comment by ivanmissu** [comment]
the ip neigh show my loadBalancer extenal ip, but can't ping
<img width="553" alt="image" src="https://user-images.githubusercontent.com/8721615/161986286-1ff36127-a3e6-4ef5-9880-3d0762bd9404.png">

**Comment by renyunkang** [comment]
I think so. You try to find the reason why the mac address of all nodes is the same, and you can use `tcpdump` to analyze where the packets are lost.
