### ISSUE TITLE
The All-Contributor badge is broken and the statistics is not complete

### ISSUE THREAD

**Issue by FeynmanZhou** [openelb/openelb#256]
- [ ] The All-Contributor badge is broken:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/40452856/161793281-7e7846a2-f42f-4897-9f65-dc12ae9e3129.png">

- [ ] I see there is only one contributor in README, is there a way to add all contributors?

**Comment by FeynmanZhou** [comment]
Hi @renyunkang ,

could you please help to take a look at this issue?

**Comment by FeynmanZhou** [comment]
Hi @renyunkang ,

could you please help to take a look at this issue?

**Comment by renyunkang** [comment]
@all-contributors please add @zheng1 for code and doc
