### ISSUE TITLE
any update about keepalived mode?

### ISSUE THREAD

**Issue by fsdrw08** [openelb/openelb#266]
as mentioned in [roadmap](https://github.com/openelb/openelb/blob/master/doc/roadmap.md), openelb should Achieve the High Availability in VIP mode based on Keepalived in version 0.7.0 at Jan, 2022, but I see tahat current release version of openelb in github still in 0.4.4.
May I know are there any update about keepalived mode in openelb?

**Comment by renyunkang** [comment]
We will release a new version in the near future. You can continue to pay attention to OpenELB.
