### ISSUE TITLE
[LFX mentoring] Support BGP policy in OpenELB

### ISSUE THREAD

**Issue by FeynmanZhou** [openelb/openelb#267]
## Project introduction

OpenELB is an open-source load balancer implementation designed for exposing the LoadBalancer type of Kubernetes services in bare metal, edge, and virtualization environments.

Currently, OpenELB supports the BGP protocol. However, the BGP policy is not fully supported in OpenELB. Therefore, based on the BGP protocol, OpenELB is supposed to support the BGP policy to enable leveraging the [GoBGP](https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md) policy feature for controlling the route advertisement.

## Required skills

* Golang
* Helm
* Docker
* Kubernetes
* BGP

## Mentor/Contact

* [Chauncey Jiang](https://github.com/chaunceyjiang/)
* [Yunkang Ren](https://github.com/renyunkang)
* [Feynman Zhou](https://github.com/FeynmanZhou)

**Comment by iharshit009** [comment]
hi @FeynmanZhou  I would be interested in working on it

**Comment by FeynmanZhou** [comment]
> hi @FeynmanZhou I would be interested in working on it

Awesome! Thanks for your interest @iharshit009 . Let me assign this issue to you.

**Comment by nyrareddy** [comment]
Hello @FeynmanZhou I am interested in this project. How many candidates can be a part of this LFX mentorship programme as I see this issue has already been assigned?

**Comment by shaoyi1997** [comment]
Hi @FeynmanZhou, I'm shaoyi, a final year CS undergrad from Singapore and I'm very interested in taking up this project under the LFX mentorship! I've started exploring the documentation and codebase and I'm looking forward to working with the OpenELB community :)

**Comment by halfrost** [comment]
Hi @FeynmanZhou, Has this task been assigned? Does anyone else have a chance?

**Comment by renyunkang** [comment]
> Hi @FeynmanZhou, I'm shaoyi, a final year CS undergrad from Singapore and I'm very interested in taking up this project under the LFX mentorship! I've started exploring the documentation and codebase and I'm looking forward to working with the OpenELB community :)

Expect your participation.

**Comment by renyunkang** [comment]
> Hi @FeynmanZhou, Has this task been assigned? Does anyone else have a chance?

You can submit an application at [this website](https://mentorship.lfx.linuxfoundation.org/project/b97a815b-6900-4a3e-a4af-7460551f933c) before 5.29, then we will select suitable candidates for development, you can learn more [here](https://docs.linuxfoundation.org/lfx/mentorship).

**Comment by renyunkang** [comment]
BGP Policy Design: https://docs.google.com/document/d/1Y6N3wuXW58Gc0qdTWCVghlHQiOycEkvheoXpAF7hq2U/edit

**Comment by amal-thundiyil** [comment]
To my fellow explorers, I have documented my LFX journey [here](https://amalthundiyil.hashnode.dev/linux-foundation-mentorship22-with-openelb) :shipit:.
