### ISSUE TITLE
why could leader of openelb must contain the random selected vip owner node's ip?

### ISSUE THREAD

**Issue by woodgear** [openelb/openelb#269]
https://github.com/openelb/openelb/blob/f9438934950189fc66561a171a1482e6e960a6dc/pkg/speaker/layer2/arp.go#L190
arpspeaker seems only worked in openelb-manager pod.

**Comment by woodgear** [comment]
@renyunkang

**Comment by renyunkang** [comment]
https://pkg.go.dev/net#IPNet.Contains. It is used to determine whether they are in a network segment, not to determine that the node contains the ip.
