### ISSUE TITLE
ipam controller update eips resource status fields return "the server could not find the requested resource" error message

### ISSUE THREAD

**Issue by lgang06** [openelb/openelb#289]
部署eips资源，更新status属性是提示 the server could not find the requested resource, 不知道那个环节配置错了，请求协助定位下问题。

**eips 配置:**
kubectl get eips bgp-eip -o yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"network.kubesphere.io/v1alpha2","kind":"Eip","metadata":{"annotations":{},"name":"bgp-eip"},"spec":{"address":"172.22.0.2-172.22.0.100","protocol":"bgp"}}
  creationTimestamp: "2022-06-29T07:46:12Z"
  finalizers:
  - finalizer.ipam.kubesphere.io/v1alpha1
  generation: 2
  name: bgp-eip
  resourceVersion: "68331237"
  selfLink: /apis/network.kubesphere.io/v1alpha2/eips/bgp-eip
  uid: 8c1d4af9-f77f-11ec-879c-001e6709bdec
spec:
  address: 172.22.0.2-172.22.0.100
  protocol: bgp
status: {}

**openelb manager pod 执行日志**

调用status update api 传递的参数:
clone=&{{Eip network.kubesphere.io/v1alpha2} {bgp-eip   /apis/network.kubesphere.io/v1alpha2/eips/bgp-eip 8c1d4af9-f77f-11ec-879c-001e6709bdec 68331237 2 2022-06-29 07:46:12 +0000 UTC <nil> <nil> map[] map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"network.kubesphere.io/v1alpha2\",\"kind\":\"Eip\",\"metadata\":{\"annotations\":{},\"name\":\"bgp-eip\"},\"spec\":{\"address\":\"172.22.0.2-172.22.0.100\",\"protocol\":\"bgp\"}}\n] [] [finalizer.ipam.kubesphere.io/v1alpha1]  []} {172.22.0.2-172.22.0.100 bgp  false false} {false 0 99 map[] 172.22.0.2 172.22.0.100 true true}}"

执行返回的错误 msg:
{"level":"error","ts":1656488789.582025,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"IPAM","request":"/bgp-eip","error":"the server could not find the requested resource (put eips.network.kubesphere.io bgp-eip)","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}

可以肯定的是，资源一定存在
kubectl get eips.network.kubesphere.io
NAME      AGE
bgp-eip   51m

api-versions信息
kubectl api-versions | grep 'kubes'
network.kubesphere.io/v1alpha1
network.kubesphere.io/v1alpha2

crd资源：
kubectl get crd | grep 'kubes'
bgpconfs.network.kubesphere.io                  2022-06-29T07:45:45Z
bgppeers.network.kubesphere.io                  2022-06-29T07:45:45Z
eips.network.kubesphere.io                      2022-06-29T07:45:45Z

环境信息:
Kubernetes ：1.14.3
go: go1.12.5
openelb: 0.5.0

**Comment by lgang06** [comment]
按照教程部署，在创建eip资源后，在openelb-manager中看到的日志。通过调试错误信息来自
https://github.com/openelb/openelb/blob/master/pkg/controllers/ipam/ipam.go 执行第185行后
应该是因为这个原因，在之后添加lb类型的svc后，exterval-ip一直是pending状态，提示 no avliable eip

no avliable eip的详细错误：
{"level":"error","ts":1656496008.8808565,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"LBController","request":"openelb-system/test4","error":"no avliable eip","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}

**Comment by renyunkang** [comment]
How do you define eip and svc.

**Comment by lgang06** [comment]
#  eip 配置：
 kubectl get eip bgp-eip -o yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"network.kubesphere.io/v1alpha2","kind":"Eip","metadata":{"annotations":{},"name":"bgp-eip"},"spec":{"address":"172.22.0.2-172.22.0.100","protocol":"bgp"}}
  creationTimestamp: "2022-06-29T09:10:19Z"
  finalizers:
  - finalizer.ipam.kubesphere.io/v1alpha1
  generation: 2
  name: bgp-eip
  resourceVersion: "68359910"
  selfLink: /apis/network.kubesphere.io/v1alpha2/eips/bgp-eip
  uid: 4c65df74-f78b-11ec-879c-001e6709bdec
spec:
  address: 172.22.0.2-172.22.0.100
  protocol: bgp
status: {}

svc配置 
 kubectl get svc test4-gateway -o yaml --namespace openelb-system
apiVersion: v1
kind: Service
metadata:
  annotations:
    eip.openelb.kubesphere.io/v1alpha2: bgp-eip
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: bgp
  creationTimestamp: "2022-06-29T09:46:24Z"
  labels:
    app.kubernetes.io/instance: test4
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway
    app.kubernetes.io/service: apisix-gateway
    app.kubernetes.io/version: 2.13.0
  name: test4-gateway
  namespace: openelb-system
  resourceVersion: "68372316"
  selfLink: /api/v1/namespaces/openelb-system/services/test4-gateway
  uid: 56c0e324-f790-11ec-879c-001e6709bdec
spec:
  clusterIP: 10.111.158.237
  externalTrafficPolicy: Cluster
  ports:
  - name: apisix-gateway
    nodePort: 60301
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: test4
    app.kubernetes.io/name: gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}




> How do you define eip and svc.



> How do you define eip and svc.

#  eip 配置：
 kubectl get eip bgp-eip -o yaml
apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"network.kubesphere.io/v1alpha2","kind":"Eip","metadata":{"annotations":{},"name":"bgp-eip"},"spec":{"address":"172.22.0.2-172.22.0.100","protocol":"bgp"}}
  creationTimestamp: "2022-06-29T09:10:19Z"
  finalizers:
  - finalizer.ipam.kubesphere.io/v1alpha1
  generation: 2
  name: bgp-eip
  resourceVersion: "68359910"
  selfLink: /apis/network.kubesphere.io/v1alpha2/eips/bgp-eip
  uid: 4c65df74-f78b-11ec-879c-001e6709bdec
spec:
  address: 172.22.0.2-172.22.0.100
  protocol: bgp
status: {}

svc配置 
 kubectl get svc test4-gateway -o yaml --namespace openelb-system
apiVersion: v1
kind: Service
metadata:
  annotations:
    eip.openelb.kubesphere.io/v1alpha2: bgp-eip
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: bgp
  creationTimestamp: "2022-06-29T09:46:24Z"
  labels:
    app.kubernetes.io/instance: test4
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway
    app.kubernetes.io/service: apisix-gateway
    app.kubernetes.io/version: 2.13.0
  name: test4-gateway
  namespace: openelb-system
  resourceVersion: "68372316"
  selfLink: /api/v1/namespaces/openelb-system/services/test4-gateway
  uid: 56c0e324-f790-11ec-879c-001e6709bdec
spec:
  clusterIP: 10.111.158.237
  externalTrafficPolicy: Cluster
  ports:
  - name: apisix-gateway
    nodePort: 60301
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: test4
    app.kubernetes.io/name: gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

**Comment by renyunkang** [comment]
Maybe you should upgrade your kubernetes version.

**Comment by lgang06** [comment]
thanks, now that the problem is solved.

**Comment by lgang06** [comment]
when run in the k8s1.14.
select a solution:
1. edit eip crd, 
    use spec.subresources,  removed spec.versions[*].subresources,
    in additionalPrinterColumns items, change  jsonPath fied to JSONPath.
2. edit openelb source code，where controller-runtime sdk are used，replace Client.Status().Update()  to Client.Update()  .
