### ISSUE TITLE
kubesphere3.3.0中，参考官网文档使用layer2模式，报no matches for kind "Eip" in version "network.kubesphere.io/v1alpha2

### ISSUE THREAD

**Issue by lutixiaya** [openelb/openelb#291]
### 官网配置：
![image](https://user-images.githubusercontent.com/48750425/176982123-cc0d6666-8c02-48c9-9418-84a43cd57fc1.png)
### 我的配置：
![image](https://user-images.githubusercontent.com/48750425/176982143-542a8b64-4e0e-4887-a923-6a133d904b3c.png)
### 报错：
```bash
[root@master1 ~]# kubectl apply -f eip.yml 
error: unable to recognize "eip.yml": no matches for kind "Eip" in version "network.kubesphere.io/v1alpha2"
```

**Comment by lutixiaya** [comment]
解决了

**Comment by xxxt** [comment]
> 解决了

怎么解决的呢，求助
`root@tools:~/openelb# cat layer2-eip.yaml 
apiVersion: network.kubesphere.io/v1alpha2
kind: Eip
metadata:
 name: layer2-eip
spec:
 address: 192.168.18.91-192.168.18.100
 interface: ens192
 protocol: layer2
root@tools:~/openelb# kubectl apply -f layer2-eip.yaml 
error: unable to recognize "layer2-eip.yaml": no matches for kind "Eip" in version "network.kubesphere.io/v1alpha2"
root@tools:~/openelb# 
`
