### ISSUE TITLE
自定义Eendpoiins后端后通过LoadBalancer访问服务，OpenELB异常退出

### ISSUE THREAD

**Issue by 905839698** [openelb/openelb#296]
**Describe the bug**
创建自定义Endpoints指向k8s-worker节点时候，通过LoadBalancer暴露服务的时候openelb异常关闭
**To Reproduce**
Steps to reproduce the behaviour:
1.创建如下yml
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: dev-demo
  labels:
    k8s-app: cadvisor
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: bgp
    eip.openelb.kubesphere.io/v1alpha2: bgp-eip
spec:
  type: LoadBalancer
  ports:
    - name: port
      port: 8080
      protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: cadvisor
  namespace: dev-demo
  labels:
    k8s-app: cadvisor
subsets:
  - addresses:
      - ip: 10.128.40.101
    ports:
      - name: port
        port: 8080
        protocol: TCP
2.通过openELB暴露服务
3.日志报错
goroutine 502 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18c0340, 0x283d6f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x18c0340, 0x283d6f0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/openelb/openelb/pkg/controllers/lb.(*ServiceReconciler).getServiceNodes(0xc000405580, 0xc0010638c0, 0x1706e50, 0xc0004051c8, 0x1b0b68e, 0xa, 0xc00104d500)
	/go/src/github.com/openelb/openelb/pkg/controllers/lb/controller.go:427 +0x867
github.com/openelb/openelb/pkg/controllers/lb.(*ServiceReconciler).callSetLoadBalancer(0xc000405580, 0xc000241750, 0xc, 0xc0002416d0, 0x7, 0x1b02d88, 0x3, 0x1d3ba40, 0xc0004fd1a0, 0xc0010638c0, ...)
	/go/src/github.com/openelb/openelb/pkg/controllers/lb/controller.go:200 +0x50
github.com/openelb/openelb/pkg/controllers/lb.(*ServiceReconciler).Reconcile(0xc000405580, 0xc000afda40, 0xe, 0xc000afda28, 0x8, 0xe6555ddf, 0xc0007b2870, 0xc0001dd108, 0xc0001dd0e0)
	/go/src/github.com/openelb/openelb/pkg/controllers/lb/controller.go:328 +0x4b0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001d0fc0, 0x1935d40, 0xc000c3fc80, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001d0fc0, 0x203000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001d0fc0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0010376c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0010376c0, 0x1d111e0, 0xc001051230, 0xc000d8ea01, 0xc0001478c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0010376c0, 0x3b9aca00, 0x0, 0x101000000000001, 0xc0001478c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133 +0xe5
k8s.io/apimachinery/pkg/util/wait.Until(0xc0010376c0, 0x3b9aca00, 0xc0001478c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x32d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x170c9e7]

**Expected behaviour**
What did you expect to happen?
正常暴露出来访问自定义后端服务
**Output**
Add the output you're seeing to help explain your problem.

**Version Info**

- Version of Kubernetes: 
- 1.19.13
- Version of OpenELB: 
- 0.4.4

**Comment by chaunceyjiang** [comment]
你的意思是 你手动创建来一个Endpoints ，给它指定来一个ip,然后把这个ep 绑定到一个svc 上，然后发现openelb报错了？ 是这样吗？

**Comment by 905839698** [comment]
是的

**Comment by renyunkang** [comment]
在 endpoints.subsets.addresses 里面指定 nodeName 后再试一下

**Comment by hb-chen** [comment]
> 在 endpoints.subsets.addresses 里面指定 nodeName 后再试一下

遇到类似的问题，用 cilium 的 ingress 创建的 endpoint 也是没有 nodeName
