### ISSUE TITLE
service配置allocateLoadBalancerNodePorts为false不生效

### ISSUE THREAD

**Issue by jionchen** [openelb/openelb#324]
apiVersion: v1
kind: Service
metadata:
  name: nginx-meta
spec:
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: http
      port: 8003
      targetPort: 80

service中配置allocateLoadBalancerNodePorts对象参数不生效

**Comment by renyunkang** [comment]
![企业微信截图_16938825388195](https://github.com/openelb/openelb/assets/33660223/efbc4748-d0e9-4574-a3b3-0fd269487259)
![企业微信截图_16938825856112](https://github.com/openelb/openelb/assets/33660223/2a46937e-90d6-4bef-b76d-c30ddea382f1)

| kubernetes version | state |
|---|---|
| v1.20 | `alpha` |
| v1.22 | `beta`, the feature gate feature switch needs to be turned on at the same time |
| v1.23 | this feature gate is enabled by default |
| v1.24 | `stable` |

So please check whether the kubernetes version you are using meets the above requirements.
