### ISSUE TITLE
在公有云使用openelb是否支持，如果使用BGP模式，需要注意什么，如果不支持有什么替代方案

### ISSUE THREAD

**Issue by kubecto** [openelb/openelb#336]
在公有云使用openelb是否支持，如果使用BGP模式，需要注意什么，如果不支持有什么替代方案

**Comment by renyunkang** [comment]
> 在公有云使用openelb是否支持，如果使用BGP模式，需要注意什么，如果不支持有什么替代方案

公有云环境还是建议使用公有云提供商所提供的方案
