### ISSUE TITLE
Use IPVS vip mode Will generate a core file

### ISSUE THREAD

**Issue by OAMchronicle** [openelb/openelb#370]
kubernetes version: 1.21.11
openelb version: 0.5.1
<img width="1287" alt="image" src="https://github.com/openelb/openelb/assets/53994620/deafdcb8-0e48-486c-b97d-ef7a2dc3fbf9">
<img width="621" alt="image" src="https://github.com/openelb/openelb/assets/53994620/94b02f03-64ff-4e5b-b6b9-27241e00bfce">

fix bug:
  github: https://github.com/OAMchronicle/kube-keepalived-vip forked from https://github.com/aledbf/kube-keepalived-vip
   Using a new version and modifying the Dockerfile again, can solve this problem.

**Comment by OAMchronicle** [comment]
将 kubesphere/kube-keepalived-vip:0.35 修改为 oamchronicle/kube-keepalived-vip:2.2.8

**Comment by renyunkang** [comment]
> 将 kubesphere/kube-keepalived-vip:0.35 修改为 oamchronicle/kube-keepalived-vip:2.2.8

It is recommended to use configmap to configure custom images. https://github.com/openelb/openelb/pull/285
