### ISSUE TITLE
https://openelb.io/网址无法访问

### ISSUE THREAD

**Issue by FlowerBirds** [openelb/openelb#404]
https://[openelb.io](https://openelb.io/)/ 无法访问，报错：ERR_SSL_UNRECOGNIZED_NAME_ALERT

**Comment by renyunkang** [comment]
There is a problem with openelb dns configuration, please visit [website-openelb.vercel.app](http://website-openelb.vercel.app/) first.

**Comment by renyunkang** [comment]
The domain `openelb.io` is now configured successfully, please refresh the page to view. If you still have problems, reopen this issue.

**Comment by FlowerBirds** [comment]
It works!

Thanks
